In [7]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import os
os.chdir("E:/Machine_Learning/Datasets/")

In [8]:
fp_df = pd.read_csv("Faceplate.csv",index_col=0)
fp_df

             Red  White  Blue  Orange  Green  Yellow
Transaction
1              1      1     0       0      1       0
2              0      1     0       1      0       0
3              0      1     1       0      0       0
4              1      1     0       1      0       0
5              1      0     1       0      0       0
6              0      1     1       0      0       0
7              1      0     1       0      0       0
8              1      1     1       0      1       0
9              1      1     1       0      0       0
10             0      0     0       0      0       1

In [9]:
fp_df = pd.read_csv("Faceplate.csv",index_col=0)
fp_df = fp_df.astype(bool)
itemsets = apriori(fp_df,min_support=0.5,use_colnames=True)
itemsets

   support itemsets
0      0.6    (Red)
1      0.7  (White)
2      0.6   (Blue)

In [10]:
fp_df = fp_df.astype(bool)
itemsets = apriori(fp_df,min_support=0.2,use_colnames=True)
itemsets

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (White, Red)
6       0.4          (Blue, Red)
7       0.2         (Green, Red)
8       0.4        (Blue, White)
9       0.2      (Orange, White)
10      0.2       (Green, White)
11      0.2   (White, Blue, Red)
12      0.2  (White, Green, Red)

In [12]:
rules =association_rules(itemsets,metric='confidence',min_threshold=0.5)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by=['confidence','lift','support'],ascending = False)

       antecedents   consequents  support  confidence      lift
15         (Green)  (White, Red)      0.2    1.000000  2.500000
4          (Green)         (Red)      0.2    1.000000  1.666667
14  (Green, White)         (Red)      0.2    1.000000  1.666667
7         (Orange)       (White)      0.2    1.000000  1.428571
8          (Green)       (White)      0.2    1.000000  1.428571
12    (Green, Red)       (White)      0.2    1.000000  1.428571
2           (Blue)         (Red)      0.4    0.666667  1.111111
3            (Red)        (Blue)      0.4    0.666667  1.111111
0            (Red)       (White)      0.4    0.666667  0.952381
5           (Blue)       (White)      0.4    0.666667  0.952381
1          (White)         (Red)      0.4    0.571429  0.952381
6          (White)        (Blue)      0.4    0.571429  0.952381
13    (White, Red)       (Green)      0.2    0.500000  2.500000
10    (White, Red)        (Blue)      0.2    0.500000  0.833333
11   (Blue, White)         (Red)      0.2    0.500000  0.833333
9      (Blue, Red)       (White)      0.2    0.500000  0.714286

## relevant rules will be those rules which have lift value greater than 1 so we filter that

In [13]:
relevant_rules = rules[rules['lift']>1]
relevant_rules

       antecedents   consequents  support  confidence      lift
2           (Blue)         (Red)      0.4    0.666667  1.111111
3            (Red)        (Blue)      0.4    0.666667  1.111111
4          (Green)         (Red)      0.2    1.000000  1.666667
7         (Orange)       (White)      0.2    1.000000  1.428571
8          (Green)       (White)      0.2    1.000000  1.428571
12    (Green, Red)       (White)      0.2    1.000000  1.428571
13    (White, Red)       (Green)      0.2    0.500000  2.500000
14  (Green, White)         (Red)      0.2    1.000000  1.666667
15         (Green)  (White, Red)      0.2    1.000000  2.500000