## Matrix Factorization

### filmtrust dataset

In [14]:
import surprise
import pandas as pd
import numpy as np
import os
os.chdir("E:/Machine_Learning/Cases_Rec_Sys/filmtrust/")

In [16]:
ratings = pd.read_csv('ratings.txt',sep=" ",names=['uid','iid','rating'])
ratings.head()

   uid  iid  rating
0    1    1     2.0
1    1    2     4.0
2    1    3     3.5
3    1    4     3.0
4    1    5     4.0

In [17]:
lowest_rating=ratings['rating'].min()
highest_rating=ratings['rating'].max()
lowest_rating,highest_rating

(np.float64(0.5), np.float64(4.0))

In [18]:
reader = surprise.Reader(rating_scale = (lowest_rating,highest_rating))
data = surprise.Dataset.load_from_df(ratings,reader)
type(data)

surprise.dataset.DatasetAutoFolds

# Grid Search CV (SVD model)

In [19]:
from surprise.model_selection import GridSearchCV
from surprise.model_selection import KFold

In [25]:
param_grid = {
    'n_epochs':[50],
    'n_factors':[100,50],
    'lr_all':np.linspace(0.001,1,5),
    'reg_all':np.linspace(0.1,0.8,5)
}
kFold = KFold(n_splits= 5,random_state=26,shuffle=True)
gs = GridSearchCV(surprise.SVD,param_grid,measures=['rmse','mae'],joblib_verbose=3,cv=kFold,n_jobs=-1)
gs.fit(data)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  96 tasks      | elapsed:   11.4s
[Parallel(n_jobs=-1)]: Done 250 out of 250 | elapsed:   24.4s finished

In [21]:
print(gs.best_score['rmse'])
print(gs.best_params['rmse'])

0.80696685870241
{'n_epochs': 50, 'n_factors': 50, 'lr_all': np.float64(0.001), 'reg_all': np.float64(0.1)}

----
## ml-100 u.data Dataset
----

In [13]:
os.chdir("E:/Machine_Learning/Cases_Rec_Sys/ml-100k/")

In [2]:
ratings = pd.read_csv('u.data',sep="\t",names=['uid','iid','rating','ts'])
ratings.drop('ts',axis=1,inplace=True)
ratings.head()

   uid  iid  rating
0  196  242       3
1  186  302       3
2   22  377       1
3  244   51       2
4  166  346       1

In [3]:
lowest_rating=ratings['rating'].min()
highest_rating=ratings['rating'].max()
lowest_rating,highest_rating

(np.int64(1), np.int64(5))

In [12]:
reader = surprise.Reader(rating_scale = (lowest_rating,highest_rating))
data = surprise.Dataset.load_from_df(ratings,reader)
type(data)

surprise.dataset.DatasetAutoFolds

In [7]:
from surprise.model_selection import GridSearchCV
from surprise.model_selection import KFold

In [8]:
param_grid = {
    'n_epochs':[50],
    'n_factors':[100,50],
    'lr_all':np.linspace(0.001,1,5),
    'reg_all':np.linspace(0.1,0.8,5)
}
kFold = KFold(n_splits= 5,random_state=26,shuffle=True)
gs = GridSearchCV(surprise.SVD,param_grid,measures=['rmse','mae'],joblib_verbose=3,cv=kFold,n_jobs=-1)
gs.fit(data)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  96 tasks      | elapsed:   35.3s
[Parallel(n_jobs=-1)]: Done 250 out of 250 | elapsed:  1.3min finished

In [10]:
print(gs.best_score['rmse'])
print(gs.best_params['rmse'])

0.947058944520809
{'n_epochs': 50, 'n_factors': 50, 'lr_all': np.float64(0.001), 'reg_all': np.float64(0.1)}