In [3]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import os
os.chdir('E:/Machine_Learning/Cases/Wisconsin')

In [14]:
bcancer = pd.read_csv('BreastCancer.csv',index_col=0)
bcancer.head()

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign

In [6]:
X,y = bcancer.drop('Class',axis=1) , bcancer['Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [7]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)
y_pred= knn.predict(X_test)
acc_score = accuracy_score(y_test,y_pred)
acc_score

0.9476190476190476

In [9]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred= knn.predict(X_test)
acc_score = accuracy_score(y_test,y_pred)
acc_score

0.9761904761904762

In [10]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred= knn.predict(X_test)
acc_score = accuracy_score(y_test,y_pred)
acc_score

0.9714285714285714

In [17]:
ks = np.arange(1,16)
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    acc = accuracy_score(y_test,y_pred)
    scores.append([k,acc])
df_scores = pd.DataFrame(scores,columns=['k','Accuracy Score'])
df_scores

     k  Accuracy Score
0    1        0.947619
1    2        0.904762
2    3        0.976190
3    4        0.952381
4    5        0.971429
5    6        0.952381
6    7        0.952381
7    8        0.952381
8    9        0.952381
9   10        0.942857
10  11        0.957143
11  12        0.952381
12  13        0.957143
13  14        0.952381
14  15        0.952381

In [21]:
df_scores.sort_values(by='Accuracy Score',ascending=False)

     k  Accuracy Score
2    3        0.976190
4    5        0.971429
10  11        0.957143
12  13        0.957143
6    7        0.952381
5    6        0.952381
3    4        0.952381
13  14        0.952381
11  12        0.952381
8    9        0.952381
7    8        0.952381
14  15        0.952381
0    1        0.947619
9   10        0.942857
1    2        0.904762

In [22]:
df_scores.nlargest(1,'Accuracy Score')

   k  Accuracy Score
2  3         0.97619