In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import root_mean_squared_error
import seaborn as sns
os.chdir("E:/Machine_Learning/Datasets")

In [2]:
job = pd.read_csv('JobSalary2.csv')
job

   S_No  Computer  Marketing  Engineer
0     1      84.0       55.0        75
1     2      90.0       53.0        70
2     3      63.0        NaN        88
3     4       NaN       50.0        77
4     5      63.0       41.0        89
5     6      75.0       54.0        85
6     7       NaN       51.0        96
7     8      77.0       64.0       105

In [9]:
job.set_index('S_No',inplace=True)

In [10]:
job.isna()

      Computer  Marketing  Engineer
S_No
1        False      False     False
2        False      False     False
3        False       True     False
4         True      False     False
5        False      False     False
6        False      False     False
7         True      False     False
8        False      False     False

In [11]:
job.isna().sum()

Computer     2
Marketing    1
Engineer     0
dtype: int64

In [12]:
job.isna().sum().sum()

np.int64(3)

### Mean Imputation

In [20]:
mu = dict(job.mean())
mu
# mu = job.mean()    THIS ALSO WORKS 
# mu


# c_mean = job['Computer'].mean()
# job['Computer'].fillna(c_mean)

{'Computer': np.float64(75.33333333333333),
 'Marketing': np.float64(52.57142857142857),
 'Engineer': np.float64(85.625)}

In [21]:
job.fillna(mu)

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000        75
2     90.000000  53.000000        70
3     63.000000  52.571429        88
4     75.333333  50.000000        77
5     63.000000  41.000000        89
6     75.000000  54.000000        85
7     75.333333  51.000000        96
8     77.000000  64.000000       105

### Median Imputation

In [23]:
med = dict(job.median())
job.fillna(med)

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0       53.0        88
4         76.0       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7         76.0       51.0        96
8         77.0       64.0       105

### Use Simlper Imputer

In [24]:
from sklearn.impute import SimpleImputer

In [31]:
imputer = SimpleImputer(strategy='mean').set_output(transform='pandas')
imputer.fit(job)
print(imputer.statistics_)
imputer.transform(job)

[75.33333333 52.57142857 85.625     ]

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0